
For UnixAos:									
Compiler.Compile Unix.OpenCL.Mod ~

For WinAos:
Compiler.Compile Win32.OpenCL.Mod ~

Examples:

Compiler.Compile

OpenCLUtils.Mod
TestOpenCLInfo.Mod
OpenCLVectorSquare.Mod
OpenCLVectorSquare1.Mod
MySimpleMandelbrotCL.Mod
MyMandelbrotCL.Mod
OpenCLEvents.Mod
MyImageRotateCL.Mod
MyJuliasetCL.Mod

~


MyMandelbrotCL.Open ~

MySimpleMandelbrotCL.Open ~

MyImageRotateCL.Open "BluebottlePic0.png" ~

MyJuliasetCL.Open ~ 







  
